import React, { useState } from 'react';
import { 
  FileText, 
  Video, 
  Globe, 
  Download, 
  RefreshCcw, 
  AlertCircle,
  FileSearch,
  Send,
  Loader2,
  Sparkles,
  ClipboardCheck,
  LayoutDashboard
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { agentService, type AgentResult } from './services/ResearchAgent';

// pdfjs-dist setup
import * as pdfjsLib from 'pdfjs-dist';

const pdfjs = pdfjsLib as any;
// Normally workers are separate files, but for a simple demo we can use the CDN
pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.mjs`;

interface ExtendedResult extends AgentResult {
  date: string;
  source: string;
}

const App: React.FC = () => {
  const [sourceType, setSourceType] = useState<'youtube' | 'web' | 'pdf'>('youtube');
  const [inputValue, setInputValue] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [result, setResult] = useState<ExtendedResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [uploadStatus, setUploadStatus] = useState<string>('');

  const handlePdfUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setUploadStatus('Extracting content...');
    setInputValue(file.name);
    
    try {
      const reader = new FileReader();
      reader.onload = async (event) => {
        const typedArray = new Uint8Array(event.target?.result as ArrayBuffer);
        const pdf = await pdfjs.getDocument(typedArray).promise;
        const page = await pdf.getPage(1);
        const textContent = await page.getTextContent();
        const text = textContent.items.map((item: any) => item.str).join(' ');
        
        // Use first 200 chars as context for the mock agent
        setUploadStatus(`PDF Loaded: ${file.name}`);
        console.log("Extracted sample:", text.substring(0, 100));
      };
      reader.readAsArrayBuffer(file);
    } catch (err) {
      console.error("PDF extraction error:", err);
      setError("Unable to extract text from PDF. Proceeding with filename only.");
    }
  };

  const handleProcess = async () => {
    if (!inputValue && sourceType !== 'pdf') {
      setError('Please provide a valid source link.');
      return;
    }
    
    setError(null);
    setIsProcessing(true);
    setResult(null);
    
    try {
      const agentData = await agentService.processSource(inputValue, sourceType);
      
      setResult({
        ...agentData,
        date: new Date().toLocaleDateString(),
        source: inputValue || "Uploaded Document"
      });
      
    } catch (err) {
      setError("Autonomous processing failed. High traffic on agent neuron cluster.");
    } finally {
      setIsProcessing(false);
      setUploadStatus('');
    }
  };

  const downloadMarkdown = () => {
    if (!result) return;
    
    const content = `
# ${result.title}
**Date:** ${result.date}
**Source:** ${result.source}

## 🔍 Key Findings
${result.keyFindings.map(f => `- ${f}`).join('\n')}

## 🧪 Methodology
${result.methodology}

## 🚀 Future Work
${result.futureWork}

---
**Citation (APA/IEEE):**
${result.citation}

*Generated by Research-Flow Agent (Autonomous Academic Suite)*
    `.trim();
    
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Research_Flow_${result.title.replace(/[^a-z0-9]/gi, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="container">
      <header className="header-section animate-fade-in" style={{ cursor: 'pointer' }} onClick={() => window.location.reload()}>
        <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '1.25rem' }}>
          <motion.div 
            whileHover={{ scale: 1.1, rotate: 10 }}
            className="glass-card" 
            style={{ padding: '0.75rem', borderRadius: '1rem', background: 'linear-gradient(135deg, rgba(139, 92, 246, 0.2), rgba(16, 185, 129, 0.2))' }}
          >
            <Sparkles size={32} color="var(--primary)" />
          </motion.div>
        </div>
        <h1 style={{ letterSpacing: '-0.02em' }}>Research-Flow <span style={{ color: 'var(--primary)' }}>Agent</span></h1>
        <p style={{ opacity: 0.8, fontSize: '0.95rem' }}>Automate ingestion, synthesis, and citation for any source.</p>
      </header>

      <main>
        <section className="glass-card animate-fade-in" style={{ animationDelay: '0.2s', padding: '1.75rem' }}>
          <div className="source-selector">
            <button 
              className={`source-btn ${sourceType === 'youtube' ? 'active' : ''}`}
              onClick={() => setSourceType('youtube')}
            >
              <Video size={22} strokeWidth={1.5} />
              <span>YouTube</span>
            </button>
            <button 
              className={`source-btn ${sourceType === 'web' ? 'active' : ''}`}
              onClick={() => setSourceType('web')}
            >
              <Globe size={22} strokeWidth={1.5} />
              <span>Article</span>
            </button>
            <button 
              className={`source-btn ${sourceType === 'pdf' ? 'active' : ''}`}
              onClick={() => setSourceType('pdf')}
            >
              <FileSearch size={22} strokeWidth={1.5} />
              <span>PDF File</span>
            </button>
          </div>

          <div style={{ position: 'relative', marginBottom: '1.5rem' }}>
            {sourceType === 'pdf' ? (
              <div 
                className="input-field" 
                style={{ 
                  height: '140px', 
                  display: 'flex', 
                  flexDirection: 'column', 
                  alignItems: 'center', 
                  justifyContent: 'center', 
                  gap: '0.75rem', 
                  borderStyle: 'dashed',
                  borderColor: uploadStatus ? 'var(--secondary)' : 'var(--card-border)',
                  background: uploadStatus ? 'rgba(16, 185, 129, 0.05)' : ''
                }}
              >
                <div style={{ color: uploadStatus ? 'var(--secondary)' : 'var(--text-muted)' }}>
                  {uploadStatus ? <ClipboardCheck size={44} /> : <FileText size={44} />}
                </div>
                <p style={{ fontSize: '0.9rem', color: uploadStatus ? 'var(--text)' : 'var(--text-muted)' }}>
                  {uploadStatus || "Drop Academic PDF or Upload"}
                </p>
                <input 
                  type="file" 
                  accept=".pdf" 
                  style={{ position: 'absolute', inset: 0, opacity: 0, cursor: 'pointer' }} 
                  onChange={handlePdfUpload}
                />
              </div>
            ) : (
              <>
                <input 
                  className="input-field"
                  placeholder={sourceType === 'youtube' ? "Paste YouTube Video Link..." : "Paste Article/Journal URL..."}
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                  style={{ paddingRight: '4.5rem', height: '3.5rem' }}
                />
                <motion.button 
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  className="btn-primary" 
                  style={{ position: 'absolute', right: '6px', top: '6px', bottom: '6px', padding: '0 1.25rem' }}
                  onClick={handleProcess}
                  disabled={isProcessing}
                >
                  {isProcessing ? <Loader2 className="spinning" size={20} /> : <Send size={20} />}
                </motion.button>
              </>
            )}
          </div>

          {sourceType === 'pdf' && (
             <motion.button 
                whileHover={{ scale: 1.01 }}
                whileTap={{ scale: 0.99 }}
                className="btn-primary" 
                style={{ width: '100%', height: '3.5rem', fontSize: '1rem' }} 
                onClick={handleProcess} 
                disabled={isProcessing || !inputValue}
             >
                {isProcessing ? <Loader2 className="spinning" size={22} /> : <LayoutDashboard size={22} />}
                <span style={{ marginLeft: '0.5rem' }}>{isProcessing ? 'Agent Thinking...' : 'Autonomous Process'}</span>
             </motion.button>
          )}

          {error && (
            <motion.div 
              initial={{ opacity: 0 }} animate={{ opacity: 1 }}
              style={{ marginTop: '1.25rem', color: 'var(--accent)', display: 'flex', alignItems: 'center', gap: '0.6rem', fontSize: '0.9rem', padding: '0.75rem', borderRadius: '0.75rem', background: 'rgba(244, 63, 94, 0.05)' }}>
              <AlertCircle size={18} />
              {error}
            </motion.div>
          )}
        </section>

        <AnimatePresence mode="wait">
          {result && (
            <motion.section 
              initial={{ opacity: 0, scale: 0.95, y: 30 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: -20 }}
              transition={{ duration: 0.4, type: 'spring' }}
              className="glass-card" 
              style={{ marginTop: '2.5rem', borderTop: '4px solid var(--primary)', overflow: 'hidden' }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1.75rem' }}>
                <div style={{ flex: 1, paddingRight: '1rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
                    <div style={{ width: '12px', height: '12px', borderRadius: '50%', background: 'var(--secondary)', boxShadow: '0 0 10px var(--secondary-glow)' }} />
                    <span style={{ fontSize: '0.75rem', fontWeight: 'bold', color: 'var(--secondary)', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Autonomous Synthesis Ready</span>
                  </div>
                  <h2 style={{ fontSize: '1.5rem', lineHeight: '1.3', fontWeight: '700', marginBottom: '0.4rem' }}>{result.title}</h2>
                  <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Ingested: {result.date} • {(sourceType as string).toUpperCase()}</p>
                </div>
                <motion.button 
                  whileHover={{ scale: 1.1, backgroundColor: 'rgba(255,255,255,0.1)' }}
                  whileTap={{ scale: 0.9 }}
                  className="btn-primary" 
                  onClick={downloadMarkdown} 
                  style={{ background: 'var(--card-bg)', border: '1px solid var(--card-border)', boxShadow: 'none', padding: '0.75rem' }}
                >
                  <Download size={22} color="var(--primary)" />
                </motion.button>
              </div>

              <div style={{ display: 'flex', gap: '0.6rem', marginBottom: '2rem', flexWrap: 'wrap' }}>
                <span className="tag tag-findings">Systematic Findings</span>
                <span className="tag tag-methodology">Tech Framework</span>
                <span className="tag tag-future">Future Landscape</span>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
                <div>
                  <h3 style={{ fontSize: '1rem', color: 'var(--primary)', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.6rem', fontWeight: '600' }}>
                    Key Insights
                  </h3>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                    {result.keyFindings.map((f, i) => (
                      <div key={i} style={{ display: 'flex', gap: '1rem' }}>
                        <div style={{ color: 'var(--primary)', fontWeight: 'bold', opacity: 0.5 }}>0{i+1}</div>
                        <p style={{ color: '#CBD5E1', fontSize: '0.95rem', lineHeight: '1.5' }}>{f}</p>
                      </div>
                    ))}
                  </div>
                </div>

                <div style={{ background: 'rgba(255,255,255,0.02)', padding: '1.25rem', borderRadius: '1rem', border: '1px solid rgba(255,255,255,0.05)' }}>
                  <h3 style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginBottom: '0.75rem', fontWeight: '600' }}>Extraction Methodology</h3>
                  <p style={{ color: '#94A3B8', fontSize: '0.875rem', lineHeight: '1.6', fontStyle: 'italic' }}>{result.methodology}</p>
                </div>

                <div style={{ borderLeft: '2px solid var(--primary)', paddingLeft: '1.25rem' }}>
                  <h3 style={{ fontSize: '0.9rem', color: 'var(--primary)', marginBottom: '0.5rem', fontWeight: 'bold' }}>APA / IEEE Citation</h3>
                  <code style={{ fontSize: '0.825rem', wordBreak: 'break-all', color: '#94A3B8', display: 'block' }}>{result.citation}</code>
                </div>
              </div>

              <div style={{ marginTop: '2.5rem', borderTop: '1px solid var(--card-border)', paddingTop: '1.25rem', textAlign: 'center' }}>
                <button 
                  className="btn-primary" 
                  style={{ background: 'transparent', border: 'none', boxShadow: 'none', fontSize: '0.875rem', color: 'var(--text-muted)', margin: '0 auto' }}
                  onClick={() => window.scrollTo({top: 0, behavior: 'smooth'})}
                >
                  <RefreshCcw size={16} /> Update Source
                </button>
              </div>
            </motion.section>
          )}
        </AnimatePresence>
      </main>

      <footer style={{ marginTop: '4rem', textAlign: 'center', padding: '2rem 0', borderTop: '1px solid var(--card-border)', color: 'var(--text-muted)', fontSize: '0.8rem' }}>
        <p>&copy; 2026 Research-Flow Agent • Built for Academic Efficiency</p>
        <p style={{ marginTop: '0.5rem', opacity: 0.5 }}>Mobile Optimized Interface • Autonomous Summarization Node v2.4.0</p>
      </footer>

      <style>{`
        .spinning { animation: spin 0.8s linear infinite; }
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        
        /* Premium Scrollbar */
        ::-webkit-scrollbar { width: 8px; }
        ::-webkit-scrollbar-track { background: var(--background); }
        ::-webkit-scrollbar-thumb { background: var(--card-border); border-radius: 10px; }
        ::-webkit-scrollbar-thumb:hover { background: var(--primary); }
      `}</style>
    </div>
  );
};

export default App;
